apps/e2e/src/client/fullSanity.ts, apps/e2e/src/indexer-client/fullSanity.ts, packages/client/src/apis/subaccount/SubaccountQueryAPI.ts, packages/contracts/abis/Endpoint.json, packages/contracts/abis/IEndpoint.json, packages/contracts/src/execute/depositCollateral.ts, packages/contracts/src/typechain-types/Endpoint.ts, packages/contracts/src/typechain-types/IEndpoint.ts, packages/contracts/src/typechain-types/factories/Endpoint__factory.ts, packages/contracts/src/typechain-types/factories/IEndpoint__factory.ts, packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/endpoints.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/serverTypes.ts
depends on https://github.com/vertex-protocol/vertex-core/pull/825
=> feat: referral API

apps/e2e/src/client/fullSanity.ts, apps/e2e/src/engine-client/fullSanity.ts, packages/client/src/apis/market/MarketQueryAPI.ts, packages/engine-client/src/EngineBaseClient.ts, packages/engine-client/src/EngineQueryClient.ts, packages/engine-client/src/types/clientQueryTypes.ts, packages/engine-client/src/types/serverQueryTypes.ts, packages/engine-client/src/utils/queryDataMappers.ts
depends on https://github.com/vertex-protocol/vertex-core/pull/864
=> feat: multi-products engine queries

apps/e2e/src/client/fullSanity.ts, apps/e2e/src/engine-client/fullSanity.ts, apps/e2e/src/indexer-client/fullSanity.ts, packages/client/src/apis/market/MarketQueryAPI.ts, packages/client/src/apis/perp/PerpQueryAPI.ts, packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/dataMappers.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/serverTypes.ts
depends on https://github.com/vertex-protocol/vertex-core/pull/894
=> feat: multi-product snapshots + perps queries

packages/indexer-client/src/dataMappers.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/serverModelTypes.ts
depends on https://github.com/vertex-protocol/vertex-core/pull/1230
=> switch interest / funding payments to annualized + add oracle price

packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/serverTypes.ts
depends on https://github.com/vertex-protocol/vertex-core/pull/1437
=> chore: add created_at to subaccounts query

packages/contracts/src/utils/subaccountInfo/subaccountInfo.ts
I found a case where initial/maint margin usage could be negative (which makes no sense), if the inital/maint/unweighted healths are negative - i.e. account is already underwater.
In the same change, im bounding margin usage from 0->100% (this is currently done on the FE already, but we reduce duplication by putting it in the SDK)
=> Bound margin usage fractions between 0 and 1

packages/client/src/apis/market/MarketExecuteAPI.ts, packages/client/src/apis/market/types.ts, packages/client/src/apis/spot/SpotExecuteAPI.ts, packages/client/src/apis/spot/types.ts, packages/client/src/apis/subaccount/SubaccountExecuteAPI.ts, packages/client/src/apis/subaccount/SubaccountQueryAPI.ts, packages/client/src/apis/subaccount/index.ts, packages/client/src/apis/subaccount/queryTypes.ts, packages/client/src/apis/subaccount/types.ts, packages/client/src/apis/types.ts, packages/client/src/apis/ws/WebSocketExecuteAPI.ts, packages/client/src/index.ts, packages/contracts/src/eip712/eip712ValueTypes.ts, packages/contracts/src/eip712/getVertexEIP712Values.ts, packages/contracts/src/eip712/orderDigest.ts, packages/contracts/src/eip712/signableRequestType.ts, packages/contracts/src/eip712/signatureParamTypes.ts, packages/contracts/src/encoding.ts, packages/engine-client/src/EngineExecuteBuilder.ts, packages/engine-client/src/EngineExecuteClient.ts, packages/engine-client/src/types/clientExecuteTypes.ts, packages/engine-client/src/types/clientQueryTypes.ts, packages/engine-client/src/types/serverExecuteTypes.ts, packages/trigger-client/src/TriggerClient.ts, packages/trigger-client/src/types/clientTypes.ts
I left a TODO originally to do this so finally got around to it. Had to rename the interfaces for EIP712 as they were conflicting with the new types in `packages/client`
=> Optional Chain ID for executes on Vertex Client

packages/contracts/src/utils/subaccountInfo/subaccountInfo.ts
https://discord.com/channels/944256846628266024/1216929724702527589/1216961391664042176
=> Zero leverage if no borrows or perps

packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/dataMappers.ts, packages/indexer-client/src/types/clientTypes.ts
[Context](https://vertex-xwn1857.slack.com/archives/C040X8JMS0G/p1711465792233949)
=> Remove arb rewards query

packages/trigger-client/src/types/serverExecuteTypes.ts
Context: https://vertex-xwn1857.slack.com/archives/C05914S2D3P/p1715801548802869
Ideally we can add this, but for now, fixing SDK
=> Remove data response from trigger execute result

apps/docs/functions/Vertex_Utils.sumBigDecimalBy.html, packages/contracts/src/utils/interest.ts, packages/contracts/src/utils/subaccountInfo/subaccountInfo.ts, packages/utils/src/asyncResult.ts, packages/utils/src/index.ts, packages/utils/src/math/BigDecimals.ts, packages/utils/src/math/decimalAdjustment.ts, packages/utils/src/math/index.ts, packages/utils/src/math/sumBigDecimalBy.ts
This PR brings in some extractable FE utils to the SDK.
=> Add some FE Utils to SDK

packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/dataMappers.ts, packages/indexer-client/src/types/clientTypes.ts
It was removed in the past but we need it for round 2
=> feat: add back support for arb rewards

package.json, yarn.lock
Bumping `ethers` to correspond with changes in web [here](https://github.com/vertex-protocol/vertex-web-monorepo/pull/2369).
=> Bump `ethers`

packages/react-client/src/context/evm/utils/getPrimaryChain.ts
`yarn build` failed because of this, pushing this fix
=> Fix getPrimaryChain

packages/contracts/src/common/deployments/core/deployment.seiTestnet.json
Updates SEI testnet deployment json as per [this Slack message](https://vertex-xwn1857.slack.com/archives/C02MP5AAYSJ/p1723022898733229?thread_ts=1722955254.347649&cid=C02MP5AAYSJ).
=> Update SEI testnet deployment json

packages/react-client/src/hooks/useIsChainType.ts
Need this for this the PR to add wSEI dismissible
=> Add isSei to useIsChainType

apps/e2e/src/indexer-client/fullSanity.ts, packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/serverTypes.ts
Support blitz points leaderboard and add rank to existing blitz points.
=> Feat/Blitz Points Leaderboard

apps/e2e/src/indexer-client/fullSanity.ts, packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/IndexerClient.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/paginatedEventsTypes.ts
Adds missing pagination endpoint
=> feat (blitz points leaderboard): add pagination endpoint

apps/e2e/src/client/fullSanity.ts, packages/client/src/apis/market/MarketQueryAPI.ts, packages/engine-client/src/EngineQueryClient.ts, packages/engine-client/src/types/clientQueryTypes.ts, packages/engine-client/src/types/serverQueryTypes.ts
Adds `getEdgeAllEngineMarkets`
=> feat (client): add getEdgeAllEngineMarkets

packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/IndexerClient.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/paginatedEventsTypes.ts, packages/indexer-client/src/types/serverTypes.ts
This PR adds interfaces and queries needed for Sonic points launch
=> Add sonic points queries

packages/contracts/src/utils/bytes32.ts
I found this bug while working on isolated, but the zero-bytes replacement breaks with something like:
`\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0002\u0000iso`
This is because we blindly remove `\u0000`, but this means that reverse conversion to bytes will not produce the same original result. We are only safe to remove trailing zero bytes.
=> Fix subaccount name conversion by only stripping trailing zero bytes

apps/e2e/src/engine-client/fullSanity.ts, packages/engine-client/src/EngineQueryClient.ts, packages/engine-client/src/types/clientQueryTypes.ts, packages/engine-client/src/types/serverQueryTypes.ts
Adds `getInsurance` to engine client.
=> feat (engine client): add insurance.

apps/e2e/src/indexer-client/fullSanity.ts, packages/indexer-client/src/IndexerBaseClient.ts, packages/indexer-client/src/dataMappers.ts, packages/indexer-client/src/types/clientTypes.ts, packages/indexer-client/src/types/serverModelTypes.ts, packages/indexer-client/src/types/serverTypes.ts
=> feat (indexer): add vrtx supply and foundation token incentives query
